export const SuiteCoreComponentId = 'suite-core';

export enum SuiteCoreStringKey {
  Common_Email = 'common_email',
  Common_Username = 'common_username',
  Common_Password = 'common_password',
  Common_Mnemonic = 'common_mnemonic',
  Common_NewPassword = 'common_newPassword',
  Common_ConfirmNewPassword = 'common_confirmNewPassword',
  Common_CurrentPassword = 'common_currentPassword',
  Common_BackupCode = 'common_backupCode',
  Common_Timezone = 'common_timezone',
  Common_EmailVerification = 'common_emailVerification',
  Common_Notification = 'common_notification',
  Common_OK = 'common_ok',
  Common_CopyToClipboard = 'common_copyToClipboard',
  Common_CopiedToClipboard = 'common_copiedToClipboard',
  Common_Dashboard = 'common_dashboard',
  Common_UnexpectedError = 'common_unexpectedError',
  Common_UseMnemonic = 'common_useMnemonic',
  Common_UsePassword = 'common_usePassword',
  Login_Title = 'login_title',
  Login_LoginButton = 'login_loginButton',
  Login_ForgotPassword = 'login_forgotPassword',
  Login_SignUp = 'login_signUp',
  Login_UseUsername = 'login_useUsername',
  Login_UseEmail = 'login_useEmail',
  Registration_ConfirmPassword = 'registration_confirmPassword',
  Registration_RegisterButton = 'registration_registerButton',
  ForgotPassword_Title = 'forgotPassword_title',
  ForgotPassword_SendResetLink = 'forgotPassword_sendResetLink',
  ForgotPassword_ResetPassword = 'forgotPassword_resetPassword',
  ForgotPassword_InvalidToken = 'forgotPassword_invalidToken',
  PasswordReset_Success = 'passwordReset_success',
  EmailVerification_Success = 'emailVerification_success',
  EmailVerification_Failed = 'emailVerification_failed',
  NoVerificationTokenProvided = 'noVerificationTokenProvided',
  ProceedToLogin = 'proceedToLogin',
  HavingTroubleContactSupport = 'havingTroubleContactSupport',
  RequestNewVerificationEmail = 'requestNewVerificationEmail',
  ApiAccess_Title = 'apiAccess_title',
  ApiAccess_TokenNotAvailable = 'apiAccess_tokenNotAvailable',
  Error_FailedToCopy = 'error_failedToCopy',
  BackupCodeRecovery_Title = 'backupCodeRecovery_title',
  BackupCodeRecovery_Login = 'backupCodeRecovery_login',
  BackupCodeRecovery_RecoverMnemonic = 'backupCodeRecovery_recoverMnemonic',
  BackupCodeRecovery_GenerateNewCodes = 'backupCodeRecovery_generateNewCodes',
  BackupCodeRecovery_CodesRemainingTemplate = 'backupCodeRecovery_codesRemainingTemplate',
  BackupCodeRecovery_YourNewCodes = 'backupCodeRecovery_yourNewCodes',
  Validation_Required = 'validation_required',
  Validation_InvalidEmail = 'validation_invalidEmail',
  Validation_UsernameRegexErrorTemplate = 'validation_usernameRegexErrorTemplate',
  Validation_PasswordMinLengthTemplate = 'validation_passwordMinLengthTemplate',
  Validation_PasswordRegexErrorTemplate = 'validation_passwordRegexErrorTemplate',
  Validation_PasswordsDifferent = 'validation_passwordsDifferent',
  Validation_PasswordMatch = 'validation_passwordMatch',
  Validation_TimezoneInvalid = 'validation_timezoneInvalid',
  Validation_MnemonicRegex = 'validation_mnemonicRegex',
  Validation_InvalidBackupCode = 'validation_invalidBackupCode',
  Validation_MnemonicOrPasswordRequired = 'validation_mnemonicOrPasswordRequired',
  Error_PasswordChange = 'error_passwordChange',
}

export const Constants = {
  UsernameRegex: /^[A-Za-z0-9]{3,30}$/,
  PasswordRegex: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
  MnemonicRegex: /^(\w+\s){11}\w+$|^(\w+\s){14}\w+$|^(\w+\s){17}\w+$|^(\w+\s){20}\w+$|^(\w+\s){23}\w+$/,
  BACKUP_CODES: {
    DisplayRegex: /^[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}$/i,
  },
};
